version: '3'

services:
  listings_db:
    restart: always
    container_name: listings-db
    image: mdillon/postgis:11
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: bungalow
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  listings_backend:
    restart: on-failure
    container_name: listings-backend
    build:
      context: .
      dockerfile: DockerFile
    entrypoint: /entrypoint.sh
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8001:8000"
    volumes:
      - .:/listings
    depends_on:
      listings_db:
        condition: service_healthy
