# Generated by Django 3.2.13 on 2022-05-03 02:15

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('num_bathrooms', models.FloatField(blank=True, null=True)),
                ('num_bedrooms', models.IntegerField(blank=True, null=True)),
                ('home_size', models.IntegerField(blank=True, null=True)),
                ('property_size', models.IntegerField(blank=True, null=True)),
                ('home_type', models.CharField(choices=[('SingleFamily', 'SingleFamily'), ('VacantResidentialLand', 'VacantResidentialLand'), ('Condominium', 'Condominium'), ('MultiFamily2To4', 'MultiFamily2To4'), ('Duplex', 'Duplex'), ('Apartment', 'Apartment')], max_length=50)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('tax_value', models.IntegerField()),
                ('tax_year', models.IntegerField()),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(max_length=2)),
                ('current_price', models.IntegerField(blank=True, null=True)),
                ('current_rent_price', models.IntegerField(blank=True, null=True)),
                ('last_sold_date', models.DateTimeField(blank=True, null=True)),
                ('last_sold_price', models.IntegerField(blank=True, null=True)),
                ('zillow_id', models.IntegerField()),
                ('zillow_link', models.URLField()),
                ('zillow_rent_estimate_price', models.IntegerField(blank=True, null=True)),
                ('zillow_rent_estimate_price_last_updated', models.DateTimeField(blank=True, null=True)),
                ('zillow_selling_price_estimate', models.IntegerField(blank=True, null=True)),
                ('zillow_selling_price_estimate_last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
